### PR TITLE
Switch to electron-forge for running/packaging

### PR DESCRIPTION
**Pull request by parkerholladay**
Fix the post install git-switch://rotate call so it does not output errors on non-mac machines

### CODE REVIEW

**Comment by parkerholladay** [comment]
*NOTE:* We need to test the packaging/signing on macOS first before we can merge this.

**Comment by jimboslicethat** [comment]
My body and mind are ready for this. Ill look over the mac signing stuff and may just add a commit on top of yours if I get it to a good place.

**Comment by jimboslicethat** [comment]
* I made some changes so that package  zipping reflects the new `./out`
* Looks like electron-forge does not yet support `osx-sign`. Im going to keep things the way they were before with that. Adding it back to `package.json`.

**Comment by jimboslicethat** [comment]
I'll have you double check the few minor changes I made. Then let's get 'er merged!

**Pull request merged**
